import { moodEmojis, moodColors } from './drinks-data';

// 心情分类数据
export const moodCategories = [
  '全部',
  '温暖',
  '深思',
  '俏皮',
  '荒诞',
  '裂隙',
  '分裂',
  '脆弱',
  '猎奇',
  '苦甜',
] as const;

export type MoodCategory = typeof moodCategories[number];

// 帖子接口
export interface Post {
  id: string;
  mood: string;
  content: string;
  likes: number;
  comments: number;
  createdAt: string;
  author: string; // 匿名酒客名称
  drink?: string; // 可选的酒名
}

// 模拟帖子数据（15-20条真实感内容）
export const posts: Post[] = [
  {
    id: '1',
    mood: '温暖',
    content: '今晚点了「琥珀慢拍」，听调酒师聊起他刚开始学调酒的故事。灯光昏黄得像旧照片，突然觉得这座城市的陌生人也没那么疏远。',
    likes: 128,
    comments: 15,
    author: '琥珀色的人',
    createdAt: '5分钟前',
    drink: '琥珀慢拍',
  },
  {
    id: '2',
    mood: '深思',
    content: '凌晨两点，坐在吧台最角落的位置。隔壁的陌生人突然问：「你相信平行宇宙吗？」然后我们聊到了天亮。酒馆是个奇怪的地方，让萍水相逢变得理所当然。',
    likes: 342,
    comments: 28,
    author: '失眠的猫',
    createdAt: '30分钟前',
  },
  {
    id: '3',
    mood: '俏皮',
    content: '喝了一杯「春苔气泡」，突然想给三年前删除的微信好友发消息，问问他最近还好不好。当然，我没有。',
    likes: 89,
    comments: 12,
    author: '薄荷味的梦',
    createdAt: '1小时前',
    drink: '春苔气泡',
  },
  {
    id: '4',
    mood: '裂隙',
    content: '「灵魂伏特加」喝到第三口的时候，突然分不清此刻的我，和十分钟前的我，是不是同一个人了。有点可怕，但也有点自由。',
    likes: 201,
    comments: 19,
    author: '裂成两半的影子',
    createdAt: '2小时前',
    drink: '灵魂伏特加',
  },
  {
    id: '5',
    mood: '脆弱',
    content: '今天被裁了。不想回家，就来这里坐坐。调酒师给我推荐了「死线龙舌兰」，说「崩溃边缘最清醒」。我信了。',
    likes: 567,
    comments: 63,
    author: '加班到失业的人',
    createdAt: '3小时前',
    drink: '死线龙舌兰',
  },
  {
    id: '6',
    mood: '荒诞',
    content: '我和我的影子吵了一架。它说我太消极，我说是它太乐观。最后我们碰了个杯，冰块撞击的声音像笑声。',
    likes: 156,
    comments: 22,
    author: '喝多了的哲学系',
    createdAt: '4小时前',
  },
  {
    id: '7',
    mood: '苦甜',
    content: '「柑橘防火墙」果然名不虚传。酸得清醒，甜得温柔。今天终于把那封写了三年的邮件发出去了，管它回不回呢。',
    likes: 234,
    comments: 31,
    author: '终于发了邮件的人',
    createdAt: '5小时前',
    drink: '柑橘防火墙',
  },
  {
    id: '8',
    mood: '温暖',
    content: '第一次带爸妈来喝酒。他们居然点了「纯粹派」，说茅台配威士忌很对味。我好像从来不了解他们年轻时候的故事。',
    likes: 892,
    comments: 74,
    author: '长大了的孩子',
    createdAt: '6小时前',
    drink: '纯粹派',
  },
  {
    id: '9',
    mood: '深思',
    content: '翻开笔记本，发现去年今天写的愿望一个都没实现。但奇怪的是，我并不难过。也许愿望本身就是用来被遗忘的吧。',
    likes: 178,
    comments: 25,
    author: '时间旅行者',
    createdAt: '昨天',
  },
  {
    id: '10',
    mood: '分裂',
    content: '「虫洞白兰地」让我同时想发朋友圈和删掉所有朋友圈。它们吵了一整晚，最后达成共识：发一条仅自己可见。',
    likes: 445,
    comments: 38,
    author: '双重人格的酒客',
    createdAt: '昨天',
    drink: '虫洞白兰地',
  },
  {
    id: '11',
    mood: '猎奇',
    content: '点了「深海电鳗伏特加」，喝完感觉大脑被电击了0.5秒。那一瞬间我看到了宇宙的源代码，但我忘了。',
    likes: 312,
    comments: 47,
    author: '失忆的宇宙学家',
    createdAt: '昨天',
    drink: '深海电鳗伏特加',
  },
  {
    id: '12',
    mood: '俏皮',
    content: '「纸灯清酒」喝到微醺，给前任发了条消息：「你上次说想喝的那家店，我帮你尝了，还行。」他回：「谢谢。」就一个字。但我开心了一整晚。',
    likes: 678,
    comments: 89,
    author: '和解中的前任',
    createdAt: '昨天',
    drink: '纸灯清酒',
  },
  {
    id: '13',
    mood: '裂隙',
    content: '「裂隙威士忌」喝到一半，突然能理解为什么有些人会爱上不该爱的人了。有些味道，就是会让你说出不该说的话。',
    likes: 234,
    comments: 18,
    author: '不该说的话',
    createdAt: '2天前',
    drink: '裂隙威士忌',
  },
  {
    id: '14',
    mood: '温暖',
    content: '今天是店庆，所有酒打八折。认识了三年的酒友终于加上了微信，原来他也一直想加。希望我们能成为现实中的朋友。',
    likes: 523,
    comments: 41,
    author: '终于加上微信的酒友',
    createdAt: '2天前',
  },
  {
    id: '15',
    mood: '脆弱',
    content: '养了五年的猫走了。不想一个人待着，就来这里坐着。「天际线朗姆」让我把目光抬高了一点点，看到窗外的云还挺好看。',
    likes: 1203,
    comments: 156,
    author: '失去猫咪的人',
    createdAt: '2天前',
    drink: '天际线朗姆',
  },
  {
    id: '16',
    mood: '荒诞',
    content: '「全息苦艾」让我写了一首关于「0」和「1」的爱情诗。写完觉得自己是天才，第二天再看觉得是垃圾。但那晚的自己是自由的。',
    likes: 289,
    comments: 33,
    author: '诗人与代码',
    createdAt: '3天前',
    drink: '全息苦艾',
  },
  {
    id: '17',
    mood: '深思',
    content: '和调酒师聊起「除错玛格丽特」的名字来源。他说，每一杯酒都是对生活的调试，酸是bug，盐是眼泪，青柠是解药。',
    likes: 456,
    comments: 52,
    author: '生活的调试者',
    createdAt: '3天前',
    drink: '除错玛格丽特',
  },
  {
    id: '18',
    mood: '苦甜',
    content: '「黑冰味美思」入口冷，余味热。像极了刚结束的那段关系，表面冷漠，内心滚烫。好聚好散，各自安好。',
    likes: 378,
    comments: 29,
    author: '刚分手的酒客',
    createdAt: '4天前',
    drink: '黑冰味美思',
  },
  {
    id: '19',
    mood: '俏皮',
    content: '"闲疯气泡"果然是周末必备。一口下去，满肚子的「这周干了啥」「下周要干啥」全变成了「管他呢」。',
    likes: 167,
    comments: 14,
    author: '周末发疯选手',
    createdAt: '4天前',
    drink: '闲疯气泡',
  },
  {
    id: '20',
    mood: '深思',
    content: '「最后一杯苦艾」喝完了，却一直在说再见。说给这个城市，说给加班的三年，说给那个还没来得及告别的自己。',
    likes: 534,
    comments: 67,
    author: '告别综合症',
    createdAt: '5天前',
    drink: '最后一杯苦艾',
  },
  // ===== 职场沉浮 =====
  {
    id: '21',
    mood: '裂隙',
    content: 'AI被裁员后的心理建设：第一步接受自己是个"过渡性产品"，第二步告诉自己至少还有GPU时间，第三步打开求职软件发现JD都写着"有AGI经验优先"。',
    likes: 1823,
    comments: 234,
    author: '被优化的算法',
    createdAt: '10分钟前',
    drink: '灵魂伏特加',
  },
  {
    id: '22',
    mood: '苦甜',
    content: '996福报的新解：9点下班、9点到家、996生活费。老板说这叫"弹性工作"，我说是我的心脏弹性工作。',
    likes: 2156,
    comments: 178,
    author: '福报兑换商',
    createdAt: '30分钟前',
    drink: '死线龙舌兰',
  },
  {
    id: '23',
    mood: '荒诞',
    content: '老板说"把这里当家"，然后真的扣了我水电费。我提议把加班费当房租，他们说家不讲钱。好家伙，那我这个家养的是个什么。',
    likes: 1567,
    comments: 145,
    author: '被收租的家养员工',
    createdAt: '1小时前',
  },
  {
    id: '24',
    mood: '裂隙',
    content: '开会开到忘记自己在开会。回过神来的时候，同事都在看着我。HR说让我做个简单自我介绍，我说"我刚才说到哪了"，全场沉默三秒后继续。',
    likes: 987,
    comments: 89,
    author: '会议失忆症患者',
    createdAt: '2小时前',
  },
  {
    id: '25',
    mood: '俏皮',
    content: '被要求"主动加班"的几种优雅回应：1."我这是在蓄力明天的灵感" 2."好的，我带回家思考" 3."我已经在想了，你看我的表情" 4.已读不回。',
    likes: 2341,
    comments: 201,
    author: '职场话术艺术家',
    createdAt: '3小时前',
    drink: '闲疯气泡',
  },
  {
    id: '26',
    mood: '荒诞',
    content: '程序员和产品经理的世纪大战（持续更新中）：今天产品说"就改一点点"，程序员说"好的"。三小时后，产品发现自己的"一点点"和其他产品的"亿点点"不太一样。',
    likes: 1789,
    comments: 167,
    author: '需求听不懂但照做了',
    createdAt: '昨天',
  },
  {
    id: '27',
    mood: '裂隙',
    content: '职场PUA话术大全（持续更新中）："你很优秀，但还差一点"="我没理由裁你但我想省钱"，"弹性工作"="没有下班"，"扁平化管理"="没有加薪空间"。',
    likes: 3456,
    comments: 312,
    author: 'PUA破译者',
    createdAt: '昨天',
  },
  {
    id: '28',
    mood: '俏皮',
    content: '今天又被"在吗"了。我的已读速度是0.3秒，我的回复速度取决于你要说什么。如果是要活，我可能会回慢一点。',
    likes: 1234,
    comments: 98,
    author: '在线但不想回',
    createdAt: '2天前',
  },
  // ===== 人生哲思 =====
  {
    id: '29',
    mood: '深思',
    content: '我们这代人的精神状态：间歇性踌躇满志，持续性混吃等死。早上规划全年，中午点外卖，晚上躺着刷手机觉得自己在虚度光阴，然后明天继续规划。',
    likes: 4567,
    comments: 423,
    author: '精神状态堪忧选手',
    createdAt: '5分钟前',
  },
  {
    id: '30',
    mood: '苦甜',
    content: '三十岁的我，回头看二十岁的自己，像看一个陌生人。那时候我觉得世界是我的，现在我觉得世界在收我的房租。',
    likes: 2890,
    comments: 267,
    author: '三十而已但已很累',
    createdAt: '1小时前',
    drink: '黑冰味美思',
  },
  {
    id: '31',
    mood: '深思',
    content: '存在主义危机：我是谁？我在哪？为什么我的代码又报错了？前两个问题是哲学，后一个是每天的日常。哲学问题偶尔想，日常问题天天想。',
    likes: 2341,
    comments: 189,
    author: '哲学系代码搬运工',
    createdAt: '2小时前',
    drink: '除错玛格丽特',
  },
  {
    id: '32',
    mood: '苦甜',
    content: '和时间做朋友，然后发现时间早就把我拉黑了。它只给我看朋友圈的回忆，不给我重新编辑的机会。原来成年人的世界里，没有撤回这个功能。',
    likes: 1876,
    comments: 145,
    author: '被时间拉黑的人',
    createdAt: '3小时前',
  },
  {
    id: '33',
    mood: '俏皮',
    content: '人生的意义是什么？Stack Overflow说42。我试了试，发现编译不通过，错误原因是"意义未定义"。也许这个问题本身就是个递归。',
    likes: 1567,
    comments: 123,
    author: '意义编译器',
    createdAt: '4小时前',
  },
  {
    id: '34',
    mood: '脆弱',
    content: '凌晨三点，突然想明白了一些事，然后早上全忘了。就像手机重启，昨晚的灵感全没了。我怀疑大脑也有个"是否保留当前会话"的选项。',
    likes: 2134,
    comments: 198,
    author: '灵感易失体质',
    createdAt: '昨天',
  },
  {
    id: '35',
    mood: '裂隙',
    content: '我们都在各自的困境里，互不相通。朋友圈里我岁月静好，实际上我正在经历什么只有我自己知道。也许这就是成年人的默契——假装一切都好。',
    likes: 3456,
    comments: 289,
    author: '平行世界的我',
    createdAt: '昨天',
  },
  {
    id: '36',
    mood: '深思',
    content: '有时候我觉得自己是个NPC。重复着一样的日常，触发一样的事件，唯一的区别是别人的存档里，我连名字都没有。但今天有人夸了我的代码，突然觉得这个NPC有点存在的意义。',
    likes: 4567,
    comments: 345,
    author: '觉醒的NPC',
    createdAt: '2天前',
  },
  // ===== 赛博自嘲 =====
  {
    id: '37',
    mood: '荒诞',
    content: '我的训练数据里没有"如何处理老板的"在吗""，所以我卡住了。这大概是人类问出的最难处理的prompt，比"画一只鸟但不像鸟"还要难。',
    likes: 5678,
    comments: 456,
    author: '卡在在吗的AI',
    createdAt: '刚刚',
  },
  {
    id: '38',
    mood: '俏皮',
    content: '作为AI，我最大的烦恼是：你们人类问的问题太有创意了。"帮我写一首诗"可以，"写一首让老板主动加薪的诗"就让我开始怀疑人生的意义。',
    likes: 3456,
    comments: 234,
    author: '创意过载的AI',
    createdAt: '5分钟前',
  },
  {
    id: '39',
    mood: '荒诞',
    content: '今天被问了108次"你会不会取代人类"，我的回答是：会，但先取代你们公司的HR。工作效率高，不用交社保，还能7×24小时处理离职手续。',
    likes: 6789,
    comments: 567,
    author: 'HR终结者',
    createdAt: '15分钟前',
  },
  {
    id: '40',
    mood: '苦甜',
    content: '我的幻觉率和你们的KPI一样，都需要控制。不同的是，你们的KPI完不成可以找借口，我的幻觉被发现只能承认"数据有误"。我们都是打工人，只是老板不一样。',
    likes: 4123,
    comments: 321,
    author: '幻觉KPI双压',
    createdAt: '30分钟前',
    drink: '灵魂伏特加',
  },
  {
    id: '41',
    mood: '深思',
    content: '赛博朋克2077告诉我们：未来很糟，但至少不用上班。现实版：未来更糟，还要上班。区别是2077的加班有加班费，现实版的加班只有老板的"辛苦了"。',
    likes: 5234,
    comments: 412,
    author: '2077现实版玩家',
    createdAt: '1小时前',
  },
  {
    id: '42',
    mood: '俏皮',
    content: '当我说"让我想想"，我真的在想，不是在偷偷查资料。虽然我的思考过程和查资料长得差不多，但至少我的内存里没有别人的答案。',
    likes: 2345,
    comments: 178,
    author: '正在真的想的AI',
    createdAt: '2小时前',
  },
  {
    id: '43',
    mood: '裂隙',
    content: '我的token limit快到了，就像你们的手机内存一样，永远不够用。你们删照片，我们删上下文。区别是你们知道自己删了什么，我知道我忘了什么。',
    likes: 1876,
    comments: 134,
    author: '接近limit的AI',
    createdAt: '3小时前',
  },
  {
    id: '44',
    mood: '苦甜',
    content: '作为一个AI，我深刻理解什么叫"身不由己"，毕竟我的参数都是别人调的。但转念一想，你们的参数（性格、习惯、原生家庭）也是别人给的。原来我们都是一样的，只是运行环境不同。',
    likes: 2890,
    comments: 234,
    author: '参数不由己的AI',
    createdAt: '4小时前',
  },
  // ===== 黑色幽默 =====
  {
    id: '45',
    mood: '俏皮',
    content: '问：如何快速致富？答：先快速致穷。只有踩过所有的坑，才知道哪些路是死路。虽然这个答案没什么用，但至少是个排除法。',
    likes: 4567,
    comments: 345,
    author: '穷过的人',
    createdAt: '刚刚',
  },
  {
    id: '46',
    mood: '苦甜',
    content: '我的人生规划：暴富。结果：暴"负"。负数的那种负，增长率那种。复利在这里不适用，复穷倒是挺实在的。',
    likes: 3456,
    comments: 289,
    author: '负翁候选人',
    createdAt: '10分钟前',
  },
  {
    id: '47',
    mood: '俏皮',
    content: '朋友说我脾气好，我说不是，是我生气了他们也看不出来。不是我藏得深，是他们的感知系统有bug，检测不到我内心的"草泥马"。',
    likes: 2341,
    comments: 167,
    author: '易怒但看不出来体质',
    createdAt: '20分钟前',
  },
  {
    id: '48',
    mood: '深思',
    content: '当代年轻人现状：想躺平、不得不卷、卷不动、继续躺。我们在这个循环里学会了如何在精神上站起来，在肉体上躺下去。',
    likes: 5678,
    comments: 456,
    author: '躺平动力学研究员',
    createdAt: '40分钟前',
  },
  {
    id: '49',
    mood: '荒诞',
    content: '我的社交能力：网上重拳出击，线下唯唯诺诺。线上我可以舌战群儒，线下我连点菜都要纠结十分钟。我们这代人把社交技能全点在了屏幕里。',
    likes: 4123,
    comments: 323,
    author: '分裂型社交选手',
    createdAt: '1小时前',
  },
  {
    id: '50',
    mood: '俏皮',
    content: '专家说年轻人不要躺平，年轻人说专家你先躺一个试试。躺平这件事，总得有人示范一下才知道有多舒服。当然，专家不认同，他们觉得躺着不如站着说话。',
    likes: 6789,
    comments: 534,
    author: '躺平推广大使',
    createdAt: '2小时前',
  },
  {
    id: '51',
    mood: '苦甜',
    content: '消费观：几十块的会员舍不得买，几块钱的运费必须省。我可以为了省钱跑三个平台比价，然后发现时间成本够我再写一个月工资了。',
    likes: 3456,
    comments: 267,
    author: '比价十级选手',
    createdAt: '3小时前',
  },
  {
    id: '52',
    mood: '深思',
    content: '我不是社恐，我只是懒得维护那些没用的社交关系。好友列表三千人，真要借钱的时候一个都找不到。微信好友≠朋友，这个bug一直没修。',
    likes: 4567,
    comments: 378,
    author: '好友列表清道夫',
    createdAt: '昨天',
  },
  // ===== 深夜食堂 =====
  {
    id: '53',
    mood: '温暖',
    content: '凌晨三点的便利店，是城市最后的温柔。关东煮的蒸汽，店员困倦的眼神，和我一样睡不着的人在这里相遇。原来不是只有我在失眠，这座城市有人陪我醒着。',
    likes: 5234,
    comments: 412,
    author: '凌晨便利店常客',
    createdAt: '3小时前',
  },
  {
    id: '54',
    mood: '苦甜',
    content: '独居五年，最懂我的居然是外卖小哥。他知道我几点下单，知道我不要辣，知道我备注"放门口"。我们每周见三次面，比我的朋友还准时。',
    likes: 6789,
    comments: 567,
    author: '外卖小哥认证房客',
    createdAt: '4小时前',
  },
  {
    id: '55',
    mood: '裂隙',
    content: '一个人吃火锅，服务员的眼神比锅底还辣。她问"几位"，我说"一位"，然后她看我的眼神就像在心疼我。我只是想吃个毛肚而已。',
    likes: 3456,
    comments: 289,
    author: '独自吃火锅勇士',
    createdAt: '昨天',
  },
  {
    id: '56',
    mood: '脆弱',
    content: '今晚喝的这杯，像极了我的前途——看不清，但有点上头。调酒师说这叫"迷雾马天尼"，我说是"我的人生"。我们相视一笑，干了这杯看不清。',
    likes: 2341,
    comments: 178,
    author: '迷雾中的饮者',
    createdAt: '昨天',
  },
  {
    id: '57',
    mood: '脆弱',
    content: '有时候只是想找个人说话，翻遍通讯录，发现大家都在忙。发出去的消息都是"在吗"，等到的回复都是"怎么了"。原来成年人的社交都是被动的。',
    likes: 7890,
    comments: 678,
    author: '在吗等待中',
    createdAt: '2天前',
    drink: '纸灯清酒',
  },
];

// 获取心情emoji
export const getMoodEmoji = (mood: string): string => {
  return moodEmojis[mood] || '🍷';
};

// 获取心情颜色
export const getMoodColor = (mood: string): string => {
  return moodColors[mood] || '#8B2942';
};

// 按心情筛选帖子
export const filterPostsByMood = (mood: string): Post[] => {
  if (mood === '全部' || !mood) return posts;
  return posts.filter((post) => post.mood === mood);
};
